const images = {
  mainlogo: require('../Assets/mainlogo.png'),
  logo: require('../Assets/logo.png'),
  menu: require('../Assets/menu.png'),
  search: require('../Assets/search.png'),
  ImageSlider: require('../Assets/Image0.png'),
  Image1: require('../Assets/Image1.png'),
  Image2: require('../Assets/Image2.png'),
  Image3: require('../Assets/Image3.png'),
  Image4: require('../Assets/Image4.png'),
  Image5: require('../Assets/Image5.png'),
  Image6: require('../Assets/Image6.png'),
  chevron: require('../Assets/chevron.png'),
  fbIcon: require('../Assets/fbIcon.png'),
  pinsertIcon: require('../Assets/pinsertIcon.png'),
  // Bottom
  profile: require('../Assets/Bottom/profile.png'),
  heart: require('../Assets/Bottom/heart.png'),
  home: require('../Assets/Bottom/home.png'),
  category: require('../Assets/Bottom/category.png'),
  // Home
  homeMain: require('../Assets/home/homeMain.jpg'),
  gift: require('../Assets/home/gift.png'),
  tags: require('../Assets/home/tags.png'),
  Check_In: require('../Assets/home/Check_In.png'),
  Brushes: require('../Assets/home/Brushes.png'),
  BuildingGel: require('../Assets/home/BuildingGel.png'),
  Decorations: require('../Assets/home/Decorations.png'),
  gel: require('../Assets/home/gel.png'),
  Liquids: require('../Assets/home/Liquids.png'),
  polybase: require('../Assets/home/polybase.png'),
  nailPolish: require('../Assets/home/nailPolish.jpg'),
  brands1: require('../Assets/home/brands1.png'),
  brands2: require('../Assets/home/brands2.jpg'),
  brands3: require('../Assets/home/brands3.jpg'),
  brands4: require('../Assets/home/brands4.jpg'),
  brands5: require('../Assets/home/brands5.jpg'),
  brands6: require('../Assets/home/brands6.png'),
  brands7: require('../Assets/home/brands7.png'),
  close: require('../Assets/login/close.png'),
  facebook: require('../Assets/login/facebook.png'),
  google: require('../Assets/login/google.png'),

};
export default images;